#!/usr/bin/env bash

apt-get update -y
apt-get install -y curl git build-essential zsh
curl -sL https://deb.nodesource.com/setup_4.x | sudo bash
apt-get install -y nodejs
npm install -g npm
chsh -s `which zsh` vagrant
