# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = 'hashicorp/precise64'
  config.vm.network :private_network, ip: '192.168.20.31'

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider :vmware_fusion do |vm|
    vm.vmw['memsize'] = 2 * 1024
    vm.vmw['numvcpus'] = 2
  end

  config.vm.provision :shell, path: 'init_script'
end
